version: "3.4"

services:

    #sql:
    #    image: "mcr.microsoft.com/mssql/server:2022-latest"
    #    container_name: sql_server2022
    #    ports: # not actually needed, because the two services are on the same network
    #        - "1433:1433" 
    #    environment:
    #        - ACCEPT_EULA=y
    #        - SA_PASSWORD=A&VeryComplex123Password

    #mongodb:
    #    image: mongo
    #    environment:
    #      - MONGO_INITDB_ROOT_USERNAME=root
    #      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    #    ports:
    #      - 27017:27017
    #    volumes:
    #      - mongodb-data:/var/lib/mongodb/data

    postgres:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgrespw
            POSTGRES_DB: ProductDb
        ports:
          - 5432:5432
        volumes:
          - psql-data:/var/lib/postresql/data
    rabbitmq:
        image: rabbitmq:management
        ports:
          - "5672:5672"  # RabbitMQ port
          - "15672:15672"  # RabbitMQ management UI port
        environment:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
    # redis:
    #     image: redis
    #     ports:
    #       - "6379:6379"
    #     volumes:
    #       - redis_data:/data

volumes:
  # redis_data:
  psql-data:
  #mongodb-data:  