version: "3.4"

services:

  postgres-product:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: ProductDb
    ports:
      - 5432:5432
    volumes:
      - psql-data-product:/var/lib/postgresql/data

  postgres-basket:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: BasketDb
    ports:
      - 5433:5432  # Expose the container port on a different host port
    volumes:
      - psql-data-basket:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"  # RabbitMQ port
      - "15672:15672"  # RabbitMQ management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  psql-data-product:
  psql-data-basket:
